// Define organizations with names and stories
var organizations = [
    { image: "images/a1.jpg", name: "A1 Boxing", story: "Young lady was suspended from school for fighting, she was defending herself from others girls bullying her, the juvenile department placed her on community service (15) hours.  At first she was apprehensive now she loves coming, she says my body has developed with muscles and I have lots of confidence and discipline." },
    { image: "images/a1.jpg", name: "A1 Boxing", story: "It's always great to see students thriving both academically and personally. A1boxing is providing a positive and supportive environment for these young men and women. The fact that they are looking forward to coming to the gym and learning new things shows their enthusiasm and engagement. The increase in retention rate by 60% is a significant achievement and reflects the impact A1boxing is making on these students' lives. Building new friendships and connections is important for their social development and overall well-being. It's heartwarming to know that parents are expressing their gratitude for the work we do. This demonstrates the value and effectiveness of the program in not only improving the lives of the students but also creating positive impacts within their families and the community. The dedication and effort invested in, are making a real difference in the lives of these students, and their success is a testament to the positive influence we are providing." },
    { image: "images/a1.jpg", name: "A1 Boxing", story: "Most of the parents are very happy with the outcome of their kid, example homework is being completed on time so he/she can come the practice, household chores are being done on a regular and the best part is wanting to stay home and not running with friends who aren't in sports." },
    { image: "images/a1.jpg", name: "A1 Boxing", story: "The retention rate is really good.  All parents compliment our progress in keeping their kid active and motivated." },
    { image: "images/a1.jpg", name: "A1 Boxing", story: "Students have been working hard getting ready for Golden Gloves, which means having good attendance and being productive at home." },
    { image: "images/ja.png", name: "Junior Acheivement", story: "This was Junior Achievement's first class of students to go through the JA Dream Accelerator! Robin Wise, JA's CEO was giving a tour at the time, and overheard a girl who was participating in the Picture Your Strengths activity say, that she had never viewed herself in such a positive way before. " },
    { image: "images/wdc.png", name: "Empowering BIPOC Girls Through Entrepreneurship", story: "Two of our students embarked on entrepreneurial journeys that involved registering their businesses with the Colorado Secretary of State, the IRS, and the City of Aurora. Gemstone Glow LLC, specializing in candles and jewelry, and Musical Sweets, offering baked goods, were both born from their efforts.Additionally, we initiated a unique class venture named Sugary Stop LLC. This endeavor is dedicated to teaching essential entrepreneurship skills to youth aged 12 to 21, all while offering a delightful range of beverages. Our vision for Sugary Stop extends beyond its immediate offerings; we aspire for it to evolve into a renowned platform for nurturing youth entrepreneurship. This is a space where young individuals can acquire crucial skills and hands-on experiences that will significantly contribute to their future success in the business world. By effectively merging practical business education with real-world application, our goal is to empower these young minds to flourish as successful entrepreneurs. We aim to provide them with a stage to display their creativity and talents. The ultimate objective is to create a business model that these students can utilize as a guide when establishing their own enterprises. This encompasses every facet, from drafting business plans, executing marketing strategies, acquiring sales and food licenses, to understanding the dynamics of a commissary kitchen. Our students also actively participated in several events, teaming up with Bonfire events at global pop-up markets on Havana Street. They gained firsthand experience by shadowing the owner of AfriCoast Patterns during events such as the pop-up market on Havana Street, the Black Arts Festival, and the Dragon Boat Festival. This hands-on exposure provided them with valuable insights into the practical operations of a business." },
    { image: "images/wdc.png", name: "Empowering BIPOC Girls Through Entrepreneurship", story: "In August, our class business, the Sugary Stop, achieved significant success through various initiatives. We strategically participated in multiple events, starting with the Taste of Ethiopia on August 5th, where we debuted and sold our flavored lemonade to a diverse and appreciative audience. This initial event set a positive tone for the month. Following the successful Taste of Ethiopia event, we participated in the Grateful Garden Farmers Market on August 9th, garnering attention and making sales from individuals seeking our beverages during their visit. The positive reception at this market further bolstered our confidence and motivated our team. One of the highlights of the month was our participation in the Havana Street Global Market on August 12th. This event allowed us to reach a wider customer base in the City of Aurora and establish our presence in the local community. The engagement and enthusiasm from attendees were encouraging, and our sales reflected the positive reception. In addition to these external events, our 7th-week program reached a successful conclusion with a final session on the morning of August 12th. During this session, we had the privilege of learning from our licensed psychologist, Tiamo Katsonga-Phiri, PhD, Director of The Trauma Disaster Recovery Clinic at Denver University. The session focused on essential themes such as Grit and Growth Mindset, as well as the significance of Selecting Mentors and Creating a Cheer team. This knowledge and guidance will undoubtedly shape our participants' future endeavors and contribute to their personal and collective growth. Overall, August was a month of accomplishment and growth for the Sugary Stop and our Empowering BIPOC Girls Through Entrepreneurship Program. We are proud of our achievements, the valuable lessons learned, and the experiences gained through these ventures." },
    { image: "images/soar.png", name: "Seeing Our Adolescents Rise (SOAR)", story: "One of our clients was having a harder time attending community activity sessions. Staff observed and reflected that he, at first, seemed to have little to no motivation to attend. However, as Staff continued to express encouragement for the Client to attend and be present in his life, he began to show up more and open up to Staff. Client was expressive and made insightful comments about his time during the sessions." },
    { image: "images/soar.png", name: "Seeing Our Adolescents Rise (SOAR)", story: "One of the kids who has been in our program since June had a difficult time, at first, engaging in sessions. He wanted to stay home and play video games for most of the day. However, through our coach continually showing up for him and planning fun activities for him to participate in, the he has been stepping more outside of his comfort zone. Our coach is still working on helping him find hobbies outside of playing video games, but he seems to enjoy mentorship much more than he did in the beginning. " },
    { image: "images/soar.png", name: "Seeing Our Adolescents Rise (SOAR)", story: "One of our clients has been in our program since the beginning of summer, and we have seen a gradual increase in engagement over the last couple of months. He continually meets with staff and is open and honest with Staff about his struggles and adversities. He continues to show up even when other parts of life, like football or friends, are active as well. " },
    { image: "images/soar.png", name: "Seeing Our Adolescents Rise (SOAR)", story: 'We have a Client who has been working with a coach and one of our therapists to work on goals such as hygiene, maintaining a good sleep schedule, routinely engaging in healthy activities, and processing her emotions. The Client has been working diligently to make progress with these goals. For example, when a stressful situation occurred, the Client spoke honestly with both her therapist and coach about the situation and felt comfortable doing so. This shows progress from when she started in the program, where she was more hesitant to share personal information. '},
    { image: "images/soar.png", name: "Seeing Our Adolescents Rise (SOAR)", story: 'One of our Clients has had a great month of progress. The client in the beginning of coaching sessions was having issues at school and reports of difficult relationship issues with brother. The client has worked with Coach around these subjects for about 2 months now. The client has developed a better perspective around the importance of being at school more often. The client has increased their attendance and improved grades. The client has also been able to improve their relationship with their brother and have not had any disagreements for a month. '},
    { image: "images/soar.png", name: "Seeing Our Adolescents Rise (SOAR)", story: 'One of our client has been working on getting out of their comfort zone and interacting with others more often. The Client is can be shy and keep to themselves. This past week, the Client decided that he wanted to attend one of our events and was able to interact with many other clients his age. He was able to step out of his comfort zone and engage in effective communication with those around him. After the event, he reflected to staff how much fun it was and enjoyed attending. '},
    { image: "images/soar.png", name: "Seeing Our Adolescents Rise (SOAR)", story: 'A.R is working with S. L. on goals that better identify with what she hopes to accomplish this year. The goals that she has set for herself include: Develop skills in baking so that Client can build upon skills she would like to use for her future career, Develop skills in different sports that Client enjoys, and Practice implementing self-care practices into everyday life in order to bring joy and relaxation. Staff, alongside TH, was able to provide the Client and her family products for hair care and other self-care items. All the work being done in conjunction with A. R. will allow her to build the confidence necessary to continuing building on the goals she has developed with the SOAR team.    '},
    { image: "images/ja.png", name: "Junior Acheivement", story: 'Here are a quote from a student and teacher that came to the JA Dream Accelerator in November. Student: "My experience with the field trip was a unique and fun experience. I hope that we can do more education fun field trips like this one when I learn more about myself."-Deegan L. Teacher: "The Dream Accelerator was a great way to get what we are learning in school about careers to come alive. I am planning to make this a regular part of our curriculum. Thank you for this opportunity.-Lisa Hollingsworth (Internship Coordinator) .This program empowers students to embark on a journey of self-discovery, providing them with tangible reports to reflect upon and share with educators, counselors, as well as parents or guardians. Beyond the tangible outcomes, participants acquire valuable critical thinking skills and techniques for self-discovery, fostering a deeper understanding of themselves.  '},
    { image: "images/ja.png", name: "Junior Acheivement", story: 'At the end of December JA Rocky Mountain received the results of a recent survey send to educators. Of the 20 educators who completed the survey, 20 out of 20 of them gave us a Net Promotor Score (NPS) of 100. We are thrilled to continue to expand our reach to students and educators throughout the metro area. '},
    { image: "images/ja.png", name: "Junior Acheivement", story: `Quotes from January JA Finance Park and JA Dream Accelerator Programming "I think that this program has my given students a crash course into the real world. And how complicated it can be. My hope is that this lesson will get them planning for a successful future" - Jordan Lobato (Teacher) " Volunteering with JA Dream Accelerator today was an amazing experience I will never forget. This is a unique opportunity for students to interactively engage with advanced technology and have open discussions about their careers, budgets, housing and more. It propels them into thinking more about their interests, skills, future and the real world. There is no doubt that their experience will leave a positive lifelong impression on them; it sure did for me as a volunteer." – Danette Goldhammer (Volunteer) “Loved seeing young adults engaged!! – Natalie Romero (Volunteer) "Thank you for making this a great experience for both the kids and adults! This has been one of my favorite volunteer events through Delta Dental of Colorado. Looking forward to the next opportunity to volunteer at Junior Achievement!” – Elisa Cardenas (Volunteer) “The best part of it all was the Reality Check. I can see how much everything costs and how much I’m going to need to make, realistically. It was all eye-opening, but especially Reality Check.” - Alexandria (Student) “It (The Dream Accelerator) was all inspiring and allowed me to expand my creativity towards my future. It represents taking control of your future. I deserve that life.” - Dash (Student) “I’ve witnessed my students’ eyes light up as they experienced the different stations of the JA Dream Accelerator. This was definitely a transformative journey that will resonate throughout their lives. I believe this type of immersive encounter not only ignited their curiosity but also empowered them to make informed career decisions for their futures.” – Tanaka Shipp (Teacher)`},
    { image: "images/acoc.jpg", name: "African Chamber of Commerce", story: "Joy Aleyo, an immigrant youth, transformed her dreams into reality through the African Chamber of Commerce Colorado's Youth Entrepreneurship Training, launching a thriving business that not only empowers her but also enriches her community. Her journey is a testament to the transformative power of education and opportunity in unlocking the potential of immigrant youth in Colorado." },
    { image: "images/sims.jpg", name: "Sims Fayola Foundation", story: "Mr. Strong is benefiting from our group so much. First, he shows up every session ready to tackle the day. Over the weeks he has continuously learned how to become better as a young black man, a brother, a friend, a son, etc. He holds his fellow cohort members accountable when they are off task or not paying attention, showing up late to the group, and/or not giving all their effort to the group. From the time I met Mr. Strong, I felt he craved Black representation and mentorship in his life. As I have closely observed his actions over the weeks it is clear to me both factors are playing a huge part in his development as a young Black man. " },
    { image: "images/sims.jpg", name: "Sims Fayola Foundation", story: "From our Director of Diversion: I had a young man with whom I did a house visit,along with Kevin Lwango from Social Services,  numerous phone calls later over three months the young man finally showed up. The young man was receptive in person to coming and joining the program. When Saturday morning came for him to show up he repeatedly was MIA. He was having trouble in School, Home, and the Community. His mother was at her wit's end. His mother reached out and the three of us met again. This time, it was at the Sims Office. During this first visit, he was medicated on something and not very communicative, as our new COO observed. The fantastic part about this is that after I built a relationship with this young man, he was not coming into the program on anything and was actively participating and giving feedback. I reminded the COO that this was the same young man who, several weeks before, was nearly despondent, and he was shocked that the two different people were the same young man with a different demeanor." },
    { image: "images/sims.jpg", name: "Sims Fayola Foundation", story: "From our faciliator: A win this week was having a great class with little to no disruptions. One of the young men I struggled with in the past won Fayola Man of the Week because he wanted to answer every question, participated in the activities, was a leader, and was a great teammate. He was so excited, and I was proud of him." },
    { image: "images/sims.jpg", name: "Sims Fayola Foundation", story: "An ongoing success story for Empowerment Zone is with a kid named LZ. When I first met L, he wanted no part of the program or what anyone had to say. He rarely said a word, and when he did, it was about guns and drugs. After a few sessions of loving on him with nonstop encouragement, it was as if a vail began to lift off of him. With each session of him seeing I genuinely care about him by being willing and available to him, he began to smile more. As we dug into each well-placed lesson created by Dr.Sims, he began to open up more because he trusted the environment I set up with no judgement, just love and insight. Now that he trusts me, he is now accepting of my guidance and trusts that I won't lead him astray. Now he is setting goals of wanting to get straight A's in school and getting a legal job so he can be successful in life, when just a month ago those goals were to make money any way possible and show his power with weapons. We are raising his awareness in life and within himself that is now giving him belief that he can make it in life. You see there is something about 'Hope' and when hope is reignited in your life, the world is yours. This kid is going from hopeLESS to hopeFUL.  Now that is power! and that is what Empowerment Zone is all about." },
    { image: "images/bbbs.png", name: "Big Brothers Big Sisters of Colorado", story: "The mentees and mentors are bonding well.  Many mentees ask if they have to leave to return to class because they want to stay.  There's a huge waiting list for 7th and 8th graders that want to be in the program, too.  One youth mentor asked if he could de-escalate a conflict between two mentees and when he addressed the situation, it was resolved and the mentees now follow that youth mentor around at each meeting feeling connected to him.  The mentees are very open to bond with their mentors." },
    { image: "images/aha.jpg", name: "Aurora Housing Authority", story: "We provided a class on gun violence and how it affects our mental, physical health, the effects on community and across the globe.  They learned that the US hat gun violence affects marginalized populations first and further perpetuates cycles of poverty.  We discussed how we can help with gun violence and what actions to take if we encounter guns.  Overall, the youth were very interactive and learned a lot form this lesson.  We held this event at the Moorhead Rec Center and the youth really enjoyed their time there and were able to engage with other youth from the program and utilize the facilities. " },
    { image: "images/jac.png", name: "Juvenile Assessment Center (JAC)", story: "We have 2 success stories from July to share.  First was a youth referred by his school for multiple behavior referrals, mental health and family dysfunction. Mother indicated serious concerns at home and school and mentioned father had not been involved for 5 years.  Family had no services in place. JAC was able to get diagnostic testing scheduled for possible ADHD and developmental delays. Worked with the school to support IEP testing and worked with DHS on basic need referrals. Youth engaged with all services.  Second was a youth referred by his school for truancy and was at risk of being unenrolled.  JAC was able to help secure services related to obtaining his GED through alternative education.  Family was also at risk of eviction and we were able to work with a community agency to help pay  their rent and utilities so mom could get caught up." },
    { image: "images/urban nature.png", name: "Urban Nature Impact", story: "One particular youth excelled in her Spanish lessons and was able to enter into a more advanced Spanish course at her high school" },
    { image: "images/urban nature.png", name: "Urban Nature Impact", story: "The paddleboarding experience was wonderful for the kids. Beng in the water was a bit foreign to several of the participants. A few just sat on the boards at the shore, while others were able to face their fear of water by actually venturing out on the water with an adult and friends. It was heart-warming  to watch their confidence grow. " },
    { image: "images/urban nature.png", name: "Urban Nature Impact", story: "This was a great month of growth for many of the youth we worked with. Two of the boys, in particular, had some very positive breakthroughs. A 17 year old showed some real promise through conditioning at the gym at House of Pain. His desire to continue with his workouts provided him the motivation he needed to thrive in other areas of his life including persoanl relationships and his education. Another young man enjoyed his experience with Paonian Records so much that he wants to pursure a career in music production. " },
    { image: "images/uplift.png", name: "Colorado Uplift", story: "Natalia - Before UpLift I was getting into fights and getting suspended from school. I was not thinking about how this would impact my future. My UpLift teacher/mentors helped me realize that my past should not determine my future. Ms Vanessa calls to check in and make sure me and my family are ok." },
    { image: "images/uplift.png", name: "Colorado Uplift", story: "Jasmine - I just moved to Denver from Pueblo because my mom just died from alcohol addiction.  I cannot live with my dad because he is addicted to drugs and unfit to care for us. I had to move up here to live with my uncle, who I do not really know. Participation in UpLift programming not only keeps me out of my uncle's house but also introduces me to supportive staff. Engaging in after-school activities, I have discovered a community that cares about my future." },
    { image: "images/uplift.png", name: "Colorado Uplift", story: "Roberto - UpLift feels like family. The experiences they have given me have changed my life. I know I have people to call when I feel like I may not make it. I have father figures now and I’ve never had that before." },
    { image: "images/uplift.png", name: "Colorado Uplift", story: "UpLift students get treated to a helicopter ride over the city. This is an awesome experience our students get to experience. This is a tradition Lem has upheld for some years now which challenges students through flying. This is many times students' first time boarding an aircraft which brings with it nerves and fears which they soar over and conquer. We are fortunate and grateful for Jeff Puckett's (pilot) generosity in serving our kids with his time and helicopter. " },
    { image: "images/uplift.png", name: "Colorado Uplift", story: "We are thrilled to report that our efforts have resulted in remarkable success stories, such as the one shared by a student who said, 'I owe my life to Colorado UpLift. My family is entrenched in gangs, but today, I am in college, pursuing a different path—all thanks to my UpLift mentors.'" },
    { image: "images/uplift.png", name: "Colorado Uplift", story: "We changed a student's view of his life's journey. We support 'you can do this!' when a young person aspires to  a career that, perhaps, they had never considered. One of our students had the opportunity to ride in a single engine, 4 passenger airplane, to have a view of the city. As they learned about the airplane and how planes fly, the question was asked - how much does an airplane like this cost. The pilot said, 'about $300,000.' The student replied, 'I'm going to make sure I don't live broke ever again!' It's all about education!" },
    { image: "images/fly.jpg", name: "Fully Liberated Youth", story: "During the month of July, one of our providers reported being reconnected with the youth they served in a meaningful way. Additionally, one of our providers reported that a youth they work with has made significant progress in several areas of his life, describing that the youth was doing much better with emotionally regulating, engaging in relationships, advocating for self, and limiting gang involvement." },
    { image: "images/fly.jpg", name: "Fully Liberated Youth", story: "Some success stories we had during the month of August were: One youth was a panelist during a presentation FLY hosted during a conference. One youth grew in their ability to advocate for their needs. One youth was facing an Aurora Municipal Court case after being ticketed for assault after being involved in a fight in school. The Court case was dismissed in August due to the Judge recognizing the support that the youth had, including his FLY mentor. That youth also attended school consistently, maintained not only passing grades but A’s and B’s, joined the skateboarding club and the Black Student Alliance at school, reported an improvement in his emotional regulation skills, and has not gotten into any trouble at school this school year." },
    { image: "images/fly.jpg", name: "Fully Liberated Youth", story: "'R,' was deeply gang-involved and was a part of the Division of Youth Services for multiple years. Now, in his early twenties, he has two children, works multiple jobs, has his own apartment, and even has his own recording studio in his home. He regularly exercises and even brings young people over to record music, keeping them out of the streets and giving them space to 'give back.' We recently spent time grieving together (all of the young people/peers we have collectively lost to the streets), and yet we simultaneously celebrate where he is and where he is going. He very easily could not be here with us, but he is. Not only is he surviving, but he is thriving. " },
    { image: "images/fly.jpg", name: "Fully Liberated Youth", story: "From a FLY Staff: I'm currently working with a youth who lives in Aurora but his family is originally from Jordan which is located in the Middle East. AM originally was charged with possession of a hand gun. Given his current living circumstances he was not able to return home and had to move with his sister in Pueblo. Due to the circumstances of his gun charge AM was placed on an ankle monitor. This ankle monitor only allowed AM to leave his home for certain instances. So AM spent roughly 3 months literally in his home. Shorty after this AM was allowed to return back home to Aurora to live with his Mother. At this time AM was able to enroll in an online high school and had his ankle monitor removed. AM was not able to return back to his home school due to the fact that he was charged with possession with a hand gun. It would have been an easy choice for AM to just give up and sit at home. However he took the initiative to enroll in school. This not only allowed him to return to school but it also demonstrated to the court system that AM's choices are that of a mature young adult that belongs in the community. " },
    { image: "images/fly.jpg", name: "Fully Liberated Youth", story: "MM began attending Cherry Creek expulsion school this month and was skeptical at first. However, the youth described receiving compliments that her teacher paid her for being prepared and doing her work. MM had cut off her ankle monitor, and despite knowing she could run, she didn't; she expressed, 'I want a better life for my babies, and running would make it harder.' This choice not to run was inspired by her vision of her future and that of her unborn child. MM continues to show improvements in her emotional development and ability to identify what makes her upset. By naming the feelings and emotions, she has been able to express her needs around these feelings. Although she hears negative talk from family members and is shamed, learning to cope with symptoms of PTSD that are coming up during this pregnancy, MM is developing positive coping strategies and skills." },
    { image: "images/fly.jpg", name: "Fully Liberated Youth", story: "Youth (LF) has developed a system where he has learned what classes he needs to be in and others that he can prepare ahead of time, that are less strenuous, and work can still be completed without being present. FLY staff has seen this youth recognize the trauma he has experienced; it has led him to make choices that have fewer negative outcomes in his personal life and leads to less triggering situations. The greatest success for this youth, is that he just acquired employment after a very long and arduous process of getting vital documents and going through an application process!" },
    { image: "images/fly.jpg", name: "Fully Liberated Youth", story: "Even though FLY staff just started seeing youth, GC, the first month saw significant life changes and success. The client was reunified with his mother after being placed in foster care. No one within the school or child welfare system had provided the family with support in getting enrolled in the school near his mother's home. We used our first two sessions to complete enrollment and case management tasks and then had to wait for the school to approve his enrollment. His lack of attendance during the month of January had nothing to do with his conduct and was the result of complex systems. Matching this youth with FLY staff, and having the time and knowledge within the system to quickly support the client and mother during this time of reunification was a success." },
    { image: "images/chic.png", name: "Collaborative Healing Initiative within Communities", story: "One of the participants in the July vision board and goal setting workshop, 'T', first met the CHIC team at a partner school. T sought mentorship and support from staff after being kicked out of her home by her mom and never had a relationship with her biological father. T has struggled with depression, mental health issues, low self esteem, and lack of confidence and direction. Since T has been a part of CHIC she has learned tools to help her deal with her confidence, she participated in basketball at her school, and was able to get a summer job working for CHIC’s summer camp, where she was a leader, and a great addition to the team. T received both academic and athletic recognition last year, and during our vision board and goal setting workshop, T showed that she is growing and becoming much more confident. She shared that CHIC has been a big part of why her confidence and attitude have improved since last year, and does not know where she would be if CHIC did not come to her school. T expressed that she is focused on school, basketball, being a leader and advocate at school, and building a stronger relationship with her family." },
    { image: "images/chic.png", name: "Collaborative Healing Initiative within Communities", story: "During the summer, 'C', an R3 participant, attended our vision board and goal planning workshop. She was able to talk through some short and long term goals, and dive deeper into some goals she wanted to achieve this school year. Her number one goal was to get caught up on her credits so she would be classified as a senior and graduate next year. She started school and experienced a lot of adversity, and struggled mentally, emotionally, and physically after losing a child. She lost her confidence, and was ready to give up. C had several one-on-one sessions with the R3 Coordinator and was supported by other CHIC team members during this time, and was able to release and reset. At a recent routine school check-in, we saw that not only were her grades mostly A’s and B’s, but she is officially classified as a senior and looking forward to starting concurrent enrollment at a technical college where she plans to start a career in health care. C has also found a therapist through one of CHIC’s mental health partners, and is feeling hopeful and at peace for the first time in a while. CHIC has been a support system for C’s entire family and it is great to see her pushing and applying herself to break generational curses and gaps in education, teen pregnancy, and mental health setbacks." },
    { image: "images/chic.png", name: "Collaborative Healing Initiative within Communities", story: "We met 'M' at a Homeless youth summit hosted by Urban Peak. M approached the CHIC table with one of the Urban Peak staff and she was very shy and short on words. M reached out later that day to ask about how she could be a part of the CHIC program. In less than a week, after catching several buses, she was sitting in the CHIC office completing an intake and meeting the entire CHIC team. M is 19 years old and lived at Urban Peak for months and was living in a hotel with a temporary housing voucher at the time of intake. Despite her living situation, she still was on track to graduate from high school and was enrolled in concurrent enrollment at Emily Griffith for her CNA certification. She worked at a senior living facility, and was just so positive and motivated despite the unforseen circumstances she had gone through. While talking to M, I learned more about her life, her goals, and her past. She had no contact with either of her parents or her younger sister, and she yearned for the love and support she was unable to get from her family. She was happy to find CHIC and vowed to be involved and committed to our programming for older participants. M has not only attended group sessions regularly, completed weekly assignments, journals, and affirmations, but she has also found her voice and is a much more confident young lady now. She has volunteered to come speak to younger girls and girls of her same age who were struggling with generational trauma. M has now graduated from high school, and completed CNA courses. She is most happy because she now has her own car and her first apartment, and she is extremely grateful to have a place to finally call home. The CHIC team is proud of M’s growth and is happy to support her and have her as a part of the CHIC family." },
    { image: "images/chic.png", name: "Collaborative Healing Initiative within Communities", story: "'E' is a participant that has attended CHIC group sessions at Jefferson Jr./Sr. High School since last year. From the first time we met E it was apparent that she was a leader, and she was positive and supportive to her fellow classmates. She has spoken about how CHIC has helped her get through some things she has gone through in her life. E models what CHIC excellence looks like by attending class, being involved in different activities and clubs at Jefferson, and by using her influence to motivate others to do what’s right. Because of E’s consistency and hard working attitude, CHIC paid for her to attend a Historical Black College and University College tour. E is currently a senior and is excited to go to college and to continue being an advocate and leader in her community. The entire CHIC team is proud of E for always showing up with a positive attitude and a smile on her face." },
    { image: "images/chic.png", name: "Collaborative Healing Initiative within Communities", story: "'J' was one of the original participants of the R3 (re-entry) program when it started in June of 2021. When we met J, she had many struggles and had a hard time with controlling her emotions and anger. She got into several incidents with family and also members in the group, and eventually decided to leave the group and run away from home. J lived on the streets with her so-called friends and got deeper and deeper into trouble, which ended with her spending time in jail and later getting physically attacked by these so-called friends while they recorded the attack on social media, which almost left her dead. J started to see the light, but still had work to do because she wanted revenge. Shortly after the incident she ended up spending months in jail. This year, J returned to our R3 olders group, which is a group of young ladies who have been a part of our younger re-entry group or who are over the age of 18. She now attends groups regularly, speaks to the younger participants about making better choices than she did, and she is making better decisions, avoiding certain “friend” groups, and is excited about her future. J is in on-going therapy and gains additional tools to keep her on the right track. J is most proud of how far she has come, and is focused on her growth and her future." },
    { image: "images/chic.png", name: "Collaborative Healing Initiative within Communities", story: "'N' is currently enrolled in the R3 older program. N started in CHIC while receiving 1:1 high level mentorship only from the CHIC team when she attended Colorado Charter High School. After graduation, N was involved in some legal trouble and got caught up with the wrong crowd, and started hanging out with a negative group of friends and family. Years later, N reached out to CHIC for financial assistance. The R3 and CHIC team sat with N during this time to help her with setting goals and addressing things in her life that were causing her so much pain and anger. N has done a lot of work to reach her goals, and works to get better each day. Last year she was awarded with tuition assistance from CHIC to attend an eyelash extension workshop. Not only did N gain a skill, she also now has an additional source of income. N recently enrolled in her second eyelash class and has hopes of getting her own studio for her clients, and would like to speak to younger girls about chasing their dreams and believing in themselves." },
    { image: "images/chic.png", name: "Collaborative Healing Initiative within Communities", story: "'L' is currently in our R3 Judicial program. L was referred to us from the juvenile justice system and had been non-compliant with every part of her probation plan. When the R3 team met with her Grandmother, who is her primary caregiver, via Zoom, they also met with her case workers, probation officer, the judge, and several other providers. Each of these people had pretty much given up hope on L. That day on the phone, the R3 team offered to support her and her Grandmother, and hoped that CHIC was the solution for L to get her life on the right track. When she joined the program, she did not see the importance of attending school, she rejected the idea of therapy, and insisted that she would not attend any group sessions at CHIC. After consistent support from the Judicial team, L now attends group sessions on a regular basis without being forced, she attends therapy weekly, she has been attending substance abuse classes, and she recently started her community service. L is happy for herself and how far she has come. She is also excited to have an opportunity at moving away from her past troubles and towards a brighter future." },
    { image: "images/dyfc.png", name: "Denver Area Youth for Christ", story: "I met a young girl at an alternative High school we partner with in Aurora. She is 16 and just gave birth to a precious baby boy. I would notice this young girl sit quietly during our teen mother support groups. To be honest she looked as if she had the weight of the world on her shoulders. After all the students left she stayed behind asking to talk. It was then that she broke down crying saying that she is strong but she is about to break. After loosing her mother a few years earlier this young woman had no reliable caretakers and was placed in the foster care system. Due to financial reasons her current foster home  could no longer keep her and she had 30 days to find a new placement for her and her son. She  said all she needs is for someone to support her while she finishes high school so she can go to college. In the weight of not having a home her mind was always focused on her pursuit of college. We immediately stepped in working to support this student, working with the school social worker and standing in the gap.. Within the last few days an amazing family stepped in to give her and her son a home and family support. Her son just turned 1 today, she is thriving in her last year of high school and she has applied to 4 HBCU colleges. She is supported by many of our leaders but more importantly I have seen first hand  life back into her hopes and dreams and she is now a thriving, young student, amazing mother,  and is starting a teen mom hotline to help other moms in need. Her story will go on to impact the lives of so many others." },
    { image: "images/dyfc.png", name: "Denver Area Youth for Christ", story: "One of our teen dads has had a little bit of a rough life and was hanging out with our youth center director, Isaiah Thomas. They were hanging out playing a game in their small groups and during this game our young person looks at Isaiah and says, “Hey man, like what are you here for - like why are you here doing what you are doing? You're a grown man!” Isaiah answered, “I'm just here for you.” And our young man said,  “Show me!” Isaiah responded by asking him to give him a day and time for him to show up and bring him lunch. On they day Isaiah was showing up with lunch the young man was texting him,  “Are you are you still coming?” And Isaiah responded that he was. When it was an hour from when they planned to meet the young man texted “You're not here are you still coming?” Isaiah responded that he was on the way and texted again when he was ten minutes away. So as Isaiah pulls up, he's looking at me he's like, 'No one ever shows up for me, everyone always gives me their word and they break it.' Isaiah gets to make promises that he can keep! This young man is still building a trusted relationship and is always looking to Isaiah and asking, 'Hey man are you gonna show up?' Isaiah gets to show up not only for this young man but also for those he loves, his girlfriend and kid. "},
    { image: "images/dyfc.png", name: "Denver Area Youth for Christ", story: 'One of our youth had nothing when they paroled back to Aurora and they had no one. Our therapist, Barb Wells, went and picked her up from the campus at Mount View the morning of her release and took her to get food, clothing, and her medication. They were able to locate an uncle that this youth once lived with. This youth has been a client of ours for the past 3 years, during that time she has graduate high school and learned relationshp skills that have allowed her to be a better mom, partner, and family member. This will be the last month of theraputic services, but since our therapist will be at our youth center, 2260 Dayton Street, they will see each other as this youth comes to our programming. It takes a team effort and this youth has built great relationships with our team.'},
    { image: "images/dyfc.png", name: "Denver Area Youth for Christ", story: "IP, a senior at New Legacy High School, was referred to our program by the principal. The principal was concerned that IP might not graduate from high school because of her low attendance and numerous missed classes. Following the referral, our staff began mentoring and discovered that the student was a young mother, living on her own without any family support. Imani had a one-year-old son and was struggling to keep up with her rent and school attendance. She was missing school because she had to work during school hours to keep up with her job and rent. After several months of mentoring, our staff learned that Imani's partner had taken on an additional job to support her, so our organization partnered with a church to  help them get caught up on rent. With this support, Imani began to thrive. Not only was she on target to graduate, but she also showed an interest in Interior Design. Our organization has a youth center opening one block away from New Legacy High School, and Imani started an Interior Design Internship with our staff. This internship provided her with high school credits, hands-on training, and experience in interior design, validating her interest in this field.  Imani helped pick out color schemes and paint for the youth center and helped develop the design concept for the center based on her peer's recommendations, showing a strong interest in setting goals for interior design and pursuing a college degree. She has grown tremendously since the start of her mentoring relationship. Imani continues to meet with her mentor once a week for mentoring, parenting support, education advancement, financial planning, and interior design internship. Our program also provides baby clothes, diapers, wipes, and other baby needs from their Free Baby Boutique to assist Imani with some of her son's needs. Additionally, she is showing interest in being a young leader at the youth center when it opens in January 2024."},
    { image: "images/dyfc.png", name: "Denver Area Youth for Christ", story: "We had the privilege of partnering with another organization and providing our young people with an opportunity in the mountains usually not given to our teen parents: three students who are usually only able to be parents. They attended Crooked Creek Ranch in Fraser, CO with their children. It is rare when a young person doesn't have their cell phone, but were given the opportunity to unplug. Without their cell phones, they were present and engage with over 450 other people from across the state. On the campgrounds are basketball courts, a hot tub, and a climbing wall. They experience a program team and speaker sharing about life and providing music and laughter all weekend. The experience helps them realize what it is like outside of the city and how they can relax and enjoy other friendships and experience healthy community!"},
    { image: "images/dyfc.png", name: "Denver Area Youth for Christ", story: "One of our students, we'll call David, was a senior at New Legacy High School last year. He is also a Father. He was struggling to graduate last year because he had to hold down a job and provide for his family. He came into our Parent Life program with his girlfriend and his baby. Both parents aspired to be better parents, graduate high school, and find their purpose. We built relationship with the couple supporting them in their goals. With their hard work and commitment to their goals and Parent Life coming alongside of them, they graduated together! He now owns and runs his own car repair shop and is mentoring other teenagers at New Legacy High School, giving back what was invested in them. He is also incorporating training for those he mentors by giving them training to work with him at the auto repair shop."},
    { image: "images/dyfc.png", name: "Denver Area Youth for Christ", story: "One of our young men after attending a fatherhood group and being mentored by our DAYFC staff started mentoring other young people through the game of basketball and was hired for this company to coach kids. His experience being a father and taking care of his family is utilizing the best of his gift sets and skills to make an impact in other's lives!"},
    { image: "images/coc.jpg", name: "Compound of Compassion", story: "Compound of Compassion was able to provide safe spaces all summer for the youth to have a place to gather without fear of violence. Youth were able to play games, enjoy dj, food, arts and crafts, spa activities and mentorship. " },
    { image: "images/bgcc.png", name: "Boys & Girls Club of Denver Metro Area", story: "This summer (2023), 55 Montview Boys & Girls Club members spent a day at Gates Camp, a summer camp facility owned and operated by BGCMD located at the base of the Indian Peaks Wilderness area west of Boulder, Colorado. Montview Club members spent the day stepping out of their comfort zones, engaging in new experiences, and building new skills while making connections with their peers, trusted adults, and nature. Surrounded by towering trees, pristine lakes, and rugged landscapes, Club members had the opportunity to explore and unleash their curiosity while participating in activities such as archery, canoeing, rock climbing, hiking, and hands-on environmental games. For many Club members, this trip to Gates Camp was their first time participating in these activities! Experiences like Gates Camp are essential in supporting positive youth development as youth who learn in and about nature show more positive attitudes about school, improved behavior, improved attendance, and overall improved academic achievement. Outdoor education has also been shown to develop independence, confidence, creativity, decision-making skills, empathy, problem-solving skills, and other social-emotional learning skills among youth (Pacific Oaks College, 2021). Montview Club members who attended Gates Camp this summer not only mastered the art of archery, tested their fishing skills, and embarked on trails throughout the mountain scenery, but also learned valuable skills like teamwork; fostered connections with mentors and friends, which is linked to lessen the likelihood of youth violence victimization and/or perpetration; and gained memories that will last a lifetime (Centers for Disease Control and Prevention, 2023). When Club members were asked to describe their Gates Camp experience in one word, they shared Gates Camp was: amazing, fun, exciting, cool, awesome, interesting, impressive, and a dream. One Club member said the only thing that could have made his visit to Gates Camp better was if he could have stayed forever! We are incredibly grateful to be able to provide Club kids with safe spaces, trusted adults, and new experiences, regardless of if they are at their Club in the Aurora or all the way in the mountains!" },
    { image: "images/bbbs.png", name: "Big Brothers Big Sisters of Colorado", story: "The success is that with recruiting mentees for the program, the number of mentees and mentors ratio works with the prescribed best practices for mentoring, 1M:4m.  There is a very positive vibe in the group and students look forward to attending the mentoring sessions." },
    { image: "images/jac.png", name: "Juvenile Assessment Center (JAC)", story: "This month we had a youth referred to us through Aurora Municipal Probation as there were concerns about youth's upcoming school year given her repeated behavior referrals last school year.  There were also concerns she needed mental health treatment.  Youth was assessed and it was discovered youth has been diagnosed with a learning disorder that had not been disclosed to the school.  This was causing youth to act out.  Mother was also concerned about youth's mental health but had no idea where to start with treatment.  JAC staff worked with mother and school to appropriately document the learning disorder and worked to have youth transfer to another school that was more equipped to deal with her specific needs. JAC staff also connected youth to in home mental health services.  The school was able to put some perimeters and plans in place to support youth before she was accepted to her new school and during that time, she had 0 behavior referrals and was doing great.  Youth has been at her new school for a couple weeks and so far, things are going great.  Youth is also engaging in the mental health treatment and even though this treatment is new, all signs point to success." },
    { image: "images/jac.png", name: "Juvenile Assessment Center (JAC)", story: "We received a referral from a middle school for a youth was struggling with her mental health and suicide attempts, running away, substance use, and multiple suspensions.  Mother was desperate for help as the police had already been involved but youth had not been officially charged yet. Youth & mother completed an assessment with one of our Clinicians and were both very open and honest about their struggles.  At this point, youth had been referred to the expulsion school, but our staff were able to connect youth with mental health supports and connect her to a mentor.  At this point, youth is actively engaging with both therapy and a mentor and has been attending the expulsion school with zero behavior incidents.  Youth has also not runaway since her assessment. There has been no police contact and youth has even made the decision to stop hanging out with her friend, which is who she was running away with and using substances. " },
    { image: "images/jac.png", name: "Juvenile Assessment Center (JAC)", story: "We received a referral from a school for a 7 year old who was struggling with mental health concerns, disruptive behavior and aggressive behavior.  The school was not sure what else to do and the parents had asked for help. During this assessment we discovered youth had a previous diagnosis of ADHD that was currently untreated and mother also mentioned she wondered if youth might be on the spectrum, however she had never followed through with testing to rule it out. After a lengthy assessment, staff aided mom in setting up a medication evaluation for ADHD, schedule a neuropsychological evaluation to determine possible spectrum disorder, and a referral was made for in home services to aid in managing his behaviors and working on parenting support. At this point, youth completed his medication evaluation and started medication to treat his ADHD.  Mother states his behavior is already night and day, especially at school.  He is scheduled for his neuropyschological evaluation the first week in December, and in home services are set to start in December as well.  The school mentioned a drastic chance already." },
    { image: "images/jac.png", name: "Juvenile Assessment Center (JAC)", story: "We received a referral from a youth's school noting concerns with behavior, attendance, mental health and that the youth was beyond the control of the parent. During the assessment, it was noted that youth's father is absent from his life (incarcerated) and he noted he acts the way he does because of that. He admitted to lying to his mother and the school on multiple occasions.  He also was honest about his attendance and grades.  He denied any mental health concerns, but after some discussion around his answers to our screening tools and some psycho education around mental health, youth was able to understand he is dealing with anxiety, depression and anger. Youth has not been in formal trouble with the police, but the school has noted he has been spending time with known gang members.Our staff referred youth to SOAR for mental health and mentoring services and as of 12/18/23, youth is actively engaging in both services through SOAR.  The school reports his attendance is getting better as well and that he has been put on a 'no pass' list, which is also helping." },
    { image: "images/jac.png", name: "Juvenile Assessment Center (JAC)", story: "We received a referral from Aurora Public Schools for a 7 year old for behavioral issues, familial issues and poor academic performance. During our work with the family, it was discovered that youth has an ADHD diagnosis and has trauma from witnessing domestic violence, which resulted in his father going to prison. Youth has not seen his father since. Youth has severe separation anxiety with mother and is currently seeking male attention. He is also suffering from night terrors and is sleepwalking. Mother is also concerned youth has dyslexia and is struggling at school because of this.  She has attended school with him in the past, which has helped, but this is not an every day option. Youth was able to get assigned a virtual therapist, but mother is concerned that virtual sessions will not be effective. We made a referral for in home services through Denver Children's Home, which we felt would be more effective for not only the youth, but also the mother. They completed the intake and have started services.  Youth also engaged with a medication evaluation and supports have been added at school to help with his separation anxiety and possible learning disabilities.  Testing will also be completed." },
    { image: "images/jac.png", name: "Juvenile Assessment Center (JAC)", story: "We assessed a youth who was referred by Aurora Municipal Court after receiving an assault charge. Youth was doing well with school, but was struggling a bit with self medication due to some gender identity struggles.  Youth was also experiencing some at risk behavior with her peers.  Youth was referred to an agency who offers one-on-one and group support for those working through gender identity.  She has already started services with this agency and is doing well!  She also has an appointment scheduled with another provider to work through her substance use/self medication concerns.  Her court case will be expunged should she complete all court requirements and that is not appearing to be a concern at this point." },
    { image: "images/bbbs.png", name: "Big Brothers Big Sisters of Colorado", story: "Results from pre surveys for both youth mentees and mentors show they hold confidence in their ability to show up for one another but are not yet confident speaking up and/or sharing feelings." },
    { image: "images/bbbs.png", name: "Big Brothers Big Sisters of Colorado", story: "A mentee in our Mrachek program shared how she was practicing setting boundaries with her friends after a session on healthy relationships and boundaries. She talked about how setting these boundaries on personal space and communication has helped her grow closer with her friends and even solved some toxic communication patterns within those friendships. Several mentees are identifying when they’re angry or upset and finding their mentor or myself to ask for a minute to cool down or safe space to decompress. This is a huge improvement as at the beginning of the year we had multiple outbursts during sessions. Now mentees are identifying their emotions and choosing to deal with them in positive, healthy ways." },
    { image: "images/strate.png", name: "The Road Called STRATE", story: "The Road Called STRATE success stories can make it hard for you to imagine that they ever experienced failure. However, the truth is that every success story involves failure. David M is a young teen that attends our STRATE Talk meetings every other Thursday. David overcome great obstacles and multiple failures which he attributes to helping shape him path to success today. David was not attending school and was hanging around the wrong people. He started talking to James Thomas, who asked him what he wanted to be in life. To his surprise David wanted to be a fireman. James asked how he planned on getting to his goal by not attending school? James was very surprised when David said my friends don't like to go to school so I hang with them. James had David sign an agreement that he would go to school every day and complete assignments. Well since the conversation with James. David has been in school and doing extremely well. We feel that simply having a conversation to point out the positive things in his life made a big difference. "},
    { image: "images/strate.png", name: "The Road Called STRATE", story: "The Road Called STRATE offered a $50.00 incentive to the current group members to bring other teens to the 'STRATE Teen Talk' group. We had one young man (Adrian) who brought 7 of his friends to the Thursday night group, and they all came back the to the next meeting and participated in the group so well. It was amazing. Hats off to Adrian for brining so many new members. This was an absolute success stories. "},
    { image: "images/strate.png", name: "The Road Called STRATE", story: "This month The Road Called STRATE did art therapy with the students to use creative expression to help individuals manage their emotions, develop self-awareness, and improve their mental health. This was a wonderful class with Bryce Baldwin, Licensed therapist. The art class helped individuals cope with stress, anxiety, depression, and other mental health issues. Art therapy encompasses a wide range of creative expressions, such as dance, music, drawing, painting, coloring, sculpting, and more. We use the art drawing with paints. The class was great. It provided a safe outlet for individuals to express themselves and explore their emotions. We have some amazing artwork that was completed through this class. "},
    { image: "images/strate.png", name: "The Road Called STRATE", story: "As our group continues to grow, we see more and more young people inviting their friends to come and join the discussions with us, but we also like to provide enjoy t the kids as well. On December 21, 023 we had about 26 young adults show up and eat food, play games and listens to the talks. It was a great turn out and positive vibes throughout the group."},
    { image: "images/strate.png", name: "The Road Called STRATE", story: "In a remarkable success story, BJ came into The Road Called STRATE August Of 2023. She faced adversity head-on and emerged victorious with the support of The Road Called STRATE. When she initially sought assistance, B was determined to secure full-time employment and revamp her resume. She also needed help with rental assistance as she had fallen behind by being unemployed for a few months Through the guidance of The Road Called STRATE's job readiness program, which she attended several times a week her resume was polished, and she received valuable job referrals. B's journey reached a triumphant milestone as she secured a full-time position at Dillard's.  In October 2023. However, her commitment to making a positive impact did not end there. Expressing a desire to give back, Ms. J became an integral part of The Road Called STRATE's Teen Talk/Gun Violence group, dedicating her time and effort to support the cause as volunteer and mentor. What sets B apart is her unwavering commitment even after achieving full-time employment. Her active involvement in the teen group has been nothing short of phenomenal. B has formed meaningful connections with many teens, contributing to the positive atmosphere of the organization."},
    { image: "images/strate.png", name: "The Road Called STRATE", story: "When our program started we had about 7-8 kids showing up. Our program has grown so much that each week we have about 20-25 students and they all seem to bring someone with them the next time that they come. This is a success in itself. I am so proud of the youth program and we want to make sure that it continues when summer comes. "},
    // Add more organizations and stories as needed
];

// Function to shuffle an array (Fisher-Yates algorithm)
function shuffleArray(array) {
    for (var i = array.length - 1; i > 0; i--) {
        var j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

// Function to create boxes with organization images
function createBoxes() {
    var boxContainer = document.getElementById("boxContainer");
    var colors = ["#63B1BC", "#F0B323", "#62269E", "#78D64B"];
    var colorIndex = 0;

    // Shuffle the organizations array
    organizations = shuffleArray(organizations);

    for (var i = 0; i < organizations.length; i++) {
        var org = organizations[i];

        var box = document.createElement("div");
        box.className = "col-md-2 mb-3";
        var innerBox = document.createElement("div");
        innerBox.className = "box";
        innerBox.style.backgroundColor = colors[colorIndex];

        // Create an image element and append it to the inner box
        var image = document.createElement("img");
        image.src = org.image;
        image.alt = org.name + " Image";
        image.className = "org-image"; // Add class for styling
        innerBox.appendChild(image);

        // Assign the click event handler to open modal with corresponding story
        innerBox.onclick = function(org) {
            return function() {
                showModal(org.name, org.story);
            };
        }(org);

        box.appendChild(innerBox);
        boxContainer.appendChild(box);

        // Alternate colors
        colorIndex = (colorIndex + 1) % colors.length;
    }
}

// Call the function to create boxes when the page loads
window.onload = createBoxes;

// Function to display modal with title and body
function showModal(title, body) {
    var modal = document.getElementById('modal');
    var modalTitle = document.getElementById('modal-title');
    var modalBody = document.getElementById('modal-body');
    modalTitle.textContent = title;
    modalBody.textContent = body;
    modal.style.display = 'block';
}

// Function to close modal
function closeModal() {
    var modal = document.getElementById('modal');
    modal.style.display = 'none';
}

